name: Android CI

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew assembleRelease
        mkdir -p ${{ github.workspace }}/apk/
        cp -rf ${{ github.workspace }}/app/build/outputs/apk/*/*.apk ${{ github.workspace }}/apk/
    - name: Upload App To Artifact
      uses: actions/upload-artifact@v4
      with:
          name: JustTrustMe
          path: ${{ github.workspace }}/apk/*.apk
